# Copyright (c) 2026 Caltech Optical Observatories
# SPDX-License-Identifier: Apache-2.0

if(NOT DEFINED SOURCE_DIR)
  message(FATAL_ERROR "SOURCE_DIR is required")
endif()

if(NOT DEFINED OUTPUT_FILE)
  message(FATAL_ERROR "OUTPUT_FILE is required")
endif()

find_package(Git QUIET)

set(build_version "unknown")

if(GIT_FOUND)
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" describe --tags --exact-match HEAD
    RESULT_VARIABLE tag_result
    OUTPUT_VARIABLE exact_tag
    ERROR_QUIET
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-parse --short=12 HEAD
    RESULT_VARIABLE hash_result
    OUTPUT_VARIABLE short_hash
    ERROR_QUIET
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" status --porcelain --untracked-files=no
    RESULT_VARIABLE status_result
    OUTPUT_VARIABLE status_output
    ERROR_QUIET
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )

  if(tag_result EQUAL 0 AND NOT exact_tag STREQUAL "")
    set(build_version "${exact_tag}")
  elseif(hash_result EQUAL 0 AND NOT short_hash STREQUAL "")
    set(build_version "${short_hash}")
  endif()

  if(status_result EQUAL 0 AND NOT status_output STREQUAL "")
    string(APPEND build_version "-dirty")
  endif()
endif()

string(REPLACE "\\" "\\\\" build_version_escaped "${build_version}")
string(REPLACE "\"" "\\\"" build_version_escaped "${build_version_escaped}")

string(CONCAT header_content
       "/* Auto-generated by app/cmake/git_build_version.cmake. */\n"
       "#ifndef HISPEC_BUILD_VERSION_H_\n"
       "#define HISPEC_BUILD_VERSION_H_\n\n"
       "#define HISPEC_BUILD_VERSION \"${build_version_escaped}\"\n\n"
       "#endif /* HISPEC_BUILD_VERSION_H_ */\n")

get_filename_component(output_dir "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${output_dir}")

if(EXISTS "${OUTPUT_FILE}")
  file(READ "${OUTPUT_FILE}" old_content)
else()
  set(old_content "")
endif()

if(NOT old_content STREQUAL header_content)
  file(WRITE "${OUTPUT_FILE}" "${header_content}")
endif()
